### ISSUE TITLE
Allow white-space at EOF and trim if before parsing

### ISSUE THREAD

**Issue by razgraf** [sablier-labs/v2-merkle-api#31]
One of the most common issues with CSV uploads has been that some editors (e.g. Microsoft Excel) add a white-space at EOF. This causes the content to fail our initial checks - frontend for sure, could be that the backend API may reject it as well. 

We should test this assumption at both levels and try to enable this kind of files and trim the content before parsing it.

**Comment by razgraf** [comment]
No, but it might be an app thing, hence the note to test at both levels.

**Comment by gavriliumircea** [comment]
I think we can close this issue because I just tested and everything seems to work just fine.
